version: '3'

networks:
  app_network:
    driver: bridge

services:
  app:
    hostname: app
    #image: aderesnes/app:flaskapp
    restart: always
    build: .
    ports:
      - 5000:5000
    links:
      - db:mysql
    depends_on:
      - db
    networks:
      - app_network

  pma:
    hostname: pma
    image: phpmyadmin
    restart: always
    links:
      - db:mysql
    depends_on:
      - db
    ports:
      - 8081:80
    environment:
      MYSQL_ROOT_PASSWORD: "{{ MysqlRootPassword }}"
      MYSQL_USER: pma
      MYSQL_PASSWORD: "{{ MySqlPmaPassword }}"
    networks:
      - app_network

  db:
    hostname: mysql
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "{{ MysqlRootPassword }}"
    volumes:
      - /var/log/mysql-db:/var/log/mysql
      - /var/lib/mysql:/var/lib/mysql
      - ./app/mysql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - app_network