---
- hosts: all
  become: true
  gather_facts: no

  tasks:
    - name: Install required system packages
      apt:
        name: [ 'apt-transport-https','ca-certificates','curl','software-properties-common','python3-pip' ]
        state: latest
        update_cache: yes

    - name: Add Docker GPG apt Key
      apt_key:
        url: "https://download.docker.com/linux/ubuntu/gpg"
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: "deb https://download.docker.com/linux/ubuntu focal stable"
        state: present

    - name: Install Docker
      apt:
        name: docker
        state: latest
        update_cache: yes

    - name: Add adminsys to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Add Docker-compose
      shell: |
        curl -L "https://github.com/docker/compose/releases/download/1.26.2/docker-compose-Linux-x86_64" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose