---
- hosts: all
  become: true
  gather_facts: no
  vars_files:
  #    - ./vars/users.yml
      - ./roles/vars/credentials.yml
      - ./roles/vars/default.yml
      - ./roles/group_vars/all/variables.yml

  tasks:
 #   - name: add users
 #     user:
 #       name: "{{ item.name }}"
 #       password: "{{ item.password | password_hash('sha512') }}"
 #       state: present
 #     with_items: "{{ user_details }}"

    - name: Apache Install
      include_tasks: ./roles/apache2.yaml

#    - name: Certbot Install
#      include_tasks: ./roles/certbot.yaml

    - name: Copy directory and files
      include_tasks: ./roles/app_directory.yaml

    - name: Execute docker-compose
      command: docker-compose -f /home/ubuntu/project/docker-compose.yml up --build -d
