---
- name: Install Certbot for SSL in Apache
  apt:
    name: ['certbot','python3-certbot-apache']
    state: latest
    update_cache: no

- name: Check hostname
  command: hostname
  register: var_hostname

- debug: msg="{{ var_hostname.stdout }}"

- name: Check if certificate already exists.
  stat:
    path: /etc/letsencrypt/live/{{ http_host }}/cert.pem
  register: letsencrypt_cert

- name: Generate new certificate if one doesn't exist.
  command: certbot run --apache --noninteractive --agree-tos --email "{{ domain_email }}" -d "{{ http_host }}" --redirect
  when: not letsencrypt_cert.stat.exists and var_hostname.stdout == "aston-awx-remote-15"
