---
- name: Install Apache2
  apt:
    name: apache2
    state: latest
    update_cache: yes

- name: enabled mod rewrite
  apache2_module:
    state: present
    name: rewrite
    force: True

- name: enabled mod proxy
  apache2_module:
    state: present
    name: proxy
    force: True

- name: enabled mod proxy_http
  apache2_module:
    state: present
    name: proxy_http
    force: True

- name: enabled mod SSL
  apache2_module:
    state: present
    name: ssl
    force: True

- name: Add Apache vhost
  copy:
    src: ./apache/vhost.conf
    dest: /etc/apache2/sites-available/

- name: Rename vhost
  command: mv /etc/apache2/sites-available/vhost.conf /etc/apache2/sites-available/"{{ domain_dev }}".conf

- name: a2ensite {{ domain_dev }}.conf
  command: a2ensite "{{ domain_dev }}".conf

- name: restart apache2
  service:
    name: apache2
    state: restarted