---
- hosts: all
  become: true
  vars_files:
      - ./vars.yml
  tasks:
      - name: add users
        user:
         name: "{{ item.name }}"
         password: "{{ item.password | password_hash('sha512') }}"
         state: present
        with_items: "{{ user_details }}"