---
- hosts: all
  become: true
  vars_files:
      - ./vars.yml

  tasks:
    - name: add users #(passwords to vaults)
      user:
        name: "{{ item.name }}"
        password: "{{ item.password | password_hash('sha512') }}"
        state: present
      with_items: "{{ user_details }}"

    - name: Install required system packages
      apt:
        name: ['apt-transport-https','ca-certificates','curl','software-properties-common','python3-pip']
        state: latest
        update_cache: yes

    - name: Docker Install
      include_tasks: ./docker.yaml

    - name: Apache Install
      include_tasks: ./apache2.yaml

    - name: Certbot Install
      include_tasks: ./certbot.yaml

    - name: Install app directory
      include_tasks: ./app_directory.yaml
